[2022-02-19 18:50:09 +0530] [50483] [DEBUG] Current configuration:
  config: config_api.py
  wsgi_app: None
  bind: ['0.0.0.0:5010']
  backlog: 2048
  workers: 1
  worker_class: sync
  threads: 4
  worker_connections: 1000
  max_requests: 0
  max_requests_jitter: 0
  timeout: 1000
  graceful_timeout: 30
  keepalive: 30
  limit_request_line: 4094
  limit_request_fields: 100
  limit_request_field_size: 8190
  reload: False
  reload_engine: auto
  reload_extra_files: []
  spew: False
  check_config: False
  print_config: False
  preload_app: False
  sendfile: None
  reuse_port: False
  chdir: /home/ideapoke/PycharmProjects/binary_classification
  daemon: False
  raw_env: []
  pidfile: None
  worker_tmp_dir: None
  user: 1000
  group: 1000
  umask: 0
  initgroups: False
  tmp_upload_dir: None
  secure_scheme_headers: {'X-FORWARDED-PROTOCOL': 'ssl', 'X-FORWARDED-PROTO': 'https', 'X-FORWARDED-SSL': 'on'}
  forwarded_allow_ips: ['127.0.0.1']
  accesslog: ./log/gunicorn_logs.log
  disable_redirect_access_to_syslog: False
  access_log_format: %(h)s %(l)s %(u)s %(t)s "%(r)s" %(s)s %(b)s "%(f)s" "%(a)s"
  errorlog: ./log/gunicorn_logs.log
  loglevel: debug
  capture_output: True
  logger_class: gunicorn.glogging.Logger
  logconfig: None
  logconfig_dict: {}
  syslog_addr: udp://localhost:514
  syslog: False
  syslog_prefix: None
  syslog_facility: user
  enable_stdio_inheritance: False
  statsd_host: None
  dogstatsd_tags: 
  statsd_prefix: 
  proc_name: None
  default_proc_name: classifier_api:app
  pythonpath: None
  paste: None
  on_starting: <function OnStarting.on_starting at 0x7f5ab8e24e50>
  on_reload: <function OnReload.on_reload at 0x7f5ab8e24f70>
  when_ready: <function when_ready at 0x7f5ab9230d30>
  pre_fork: <function pre_fork at 0x7f5ab9230c10>
  post_fork: <function post_fork at 0x7f5ab9230b80>
  post_worker_init: <function PostWorkerInit.post_worker_init at 0x7f5ab8db6430>
  worker_int: <function worker_int at 0x7f5ab9230dc0>
  worker_abort: <function worker_abort at 0x7f5ab9230e50>
  pre_exec: <function pre_exec at 0x7f5ab9230ca0>
  pre_request: <function PreRequest.pre_request at 0x7f5ab8db68b0>
  post_request: <function PostRequest.post_request at 0x7f5ab8db6940>
  child_exit: <function ChildExit.child_exit at 0x7f5ab8db6a60>
  worker_exit: <function WorkerExit.worker_exit at 0x7f5ab8db6b80>
  nworkers_changed: <function NumWorkersChanged.nworkers_changed at 0x7f5ab8db6ca0>
  on_exit: <function OnExit.on_exit at 0x7f5ab8db6dc0>
  proxy_protocol: False
  proxy_allow_ips: ['127.0.0.1']
  keyfile: None
  certfile: None
  ssl_version: 2
  cert_reqs: 0
  ca_certs: None
  suppress_ragged_eofs: True
  do_handshake_on_connect: False
  ciphers: None
  raw_paste_global_conf: []
  strip_header_spaces: False
[2022-02-19 18:50:09 +0530] [50483] [INFO] Starting gunicorn 20.1.0
[2022-02-19 18:50:09 +0530] [50483] [DEBUG] Arbiter booted
[2022-02-19 18:50:09 +0530] [50483] [INFO] Listening at: http://0.0.0.0:5010 (50483)
[2022-02-19 18:50:09 +0530] [50483] [INFO] Using worker: gthread
[2022-02-19 18:50:09 +0530] [50483] [INFO] Server is ready. Spawning workers
[2022-02-19 18:50:09 +0530] [50485] [INFO] Booting worker with pid: 50485
[2022-02-19 18:50:09 +0530] [50485] [INFO] Worker spawned (pid: 50485)
[2022-02-19 18:50:09 +0530] [50483] [DEBUG] 1 workers
2022-02-19 18:50:10.563057: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-02-19 18:50:10.563099: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2022-02-19 18:50:12.758599: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2022-02-19 18:50:12.758703: W tensorflow/stream_executor/cuda/cuda_driver.cc:269] failed call to cuInit: UNKNOWN ERROR (303)
2022-02-19 18:50:12.758766: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (Laptop-Rakshit): /proc/driver/nvidia/version does not exist
2022-02-19 18:50:12.766799: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-02-19 18:50:13.967820: W tensorflow/core/framework/cpu_allocator_impl.cc:82] Allocation of 1009375000 exceeds 10% of free system memory.
[2022-02-19 18:50:14 +0530] [50483] [INFO] Handling signal: int
[2022-02-19 18:50:25 +0530] [50485] [INFO] worker received INT or QUIT signal
[2022-02-19 18:50:25 +0530] [50485] [DEBUG] 
# Thread: MainThread(140027645126464)
File: "/home/ideapoke/PycharmProjects/binary_classification/venv/bin/gunicorn", line 8, in <module>
  sys.exit(run())
File: "/home/ideapoke/PycharmProjects/binary_classification/venv/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 67, in run
  WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
File: "/home/ideapoke/PycharmProjects/binary_classification/venv/lib/python3.8/site-packages/gunicorn/app/base.py", line 231, in run
  super().run()
File: "/home/ideapoke/PycharmProjects/binary_classification/venv/lib/python3.8/site-packages/gunicorn/app/base.py", line 72, in run
  Arbiter(self).run()
File: "/home/ideapoke/PycharmProjects/binary_classification/venv/lib/python3.8/site-packages/gunicorn/arbiter.py", line 202, in run
  self.manage_workers()
File: "/home/ideapoke/PycharmProjects/binary_classification/venv/lib/python3.8/site-packages/gunicorn/arbiter.py", line 551, in manage_workers
  self.spawn_workers()
File: "/home/ideapoke/PycharmProjects/binary_classification/venv/lib/python3.8/site-packages/gunicorn/arbiter.py", line 622, in spawn_workers
  self.spawn_worker()
File: "/home/ideapoke/PycharmProjects/binary_classification/venv/lib/python3.8/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
  worker.init_process()
File: "/home/ideapoke/PycharmProjects/binary_classification/venv/lib/python3.8/site-packages/gunicorn/workers/gthread.py", line 92, in init_process
  super().init_process()
File: "/home/ideapoke/PycharmProjects/binary_classification/venv/lib/python3.8/site-packages/gunicorn/workers/base.py", line 134, in init_process
  self.load_wsgi()
File: "/home/ideapoke/PycharmProjects/binary_classification/venv/lib/python3.8/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
  self.wsgi = self.app.wsgi()
File: "/home/ideapoke/PycharmProjects/binary_classification/venv/lib/python3.8/site-packages/gunicorn/app/base.py", line 67, in wsgi
  self.callable = self.load()
File: "/home/ideapoke/PycharmProjects/binary_classification/venv/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
  return self.load_wsgiapp()
File: "/home/ideapoke/PycharmProjects/binary_classification/venv/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
  return util.import_app(self.app_uri)
File: "/home/ideapoke/PycharmProjects/binary_classification/venv/lib/python3.8/site-packages/gunicorn/util.py", line 359, in import_app
  mod = importlib.import_module(module)
File: "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
  return _bootstrap._gcd_import(name[level:], package, level)
File: "<frozen importlib._bootstrap>", line 1014, in _gcd_import
File: "<frozen importlib._bootstrap>", line 991, in _find_and_load
File: "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
File: "<frozen importlib._bootstrap>", line 671, in _load_unlocked
File: "<frozen importlib._bootstrap_external>", line 848, in exec_module
File: "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
File: "/home/ideapoke/PycharmProjects/binary_classification/classifier_api.py", line 5, in <module>
  from lstm_classifier import prediction_pipeline
File: "<frozen importlib._bootstrap>", line 991, in _find_and_load
File: "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
File: "<frozen importlib._bootstrap>", line 671, in _load_unlocked
File: "<frozen importlib._bootstrap_external>", line 848, in exec_module
File: "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
File: "/home/ideapoke/PycharmProjects/binary_classification/lstm_classifier.py", line 10, in <module>
  embeddings = hub.load("https://tfhub.dev/google/Wiki-words-250/2")
File: "/home/ideapoke/PycharmProjects/binary_classification/venv/lib/python3.8/site-packages/tensorflow_hub/module_v2.py", line 106, in load
  obj = tf.compat.v1.saved_model.load_v2(module_path, tags=tags)
File: "/home/ideapoke/PycharmProjects/binary_classification/venv/lib/python3.8/site-packages/tensorflow/python/saved_model/load.py", line 936, in load
  result = load_internal(export_dir, tags, options)["root"]
File: "/home/ideapoke/PycharmProjects/binary_classification/venv/lib/python3.8/site-packages/tensorflow/python/saved_model/load.py", line 974, in load_internal
  loader = loader_cls(object_graph_proto, saved_model_proto, export_dir,
File: "/home/ideapoke/PycharmProjects/binary_classification/venv/lib/python3.8/site-packages/tensorflow/python/saved_model/load.py", line 187, in __init__
  self._restore_checkpoint()
File: "/home/ideapoke/PycharmProjects/binary_classification/venv/lib/python3.8/site-packages/tensorflow/python/saved_model/load.py", line 560, in _restore_checkpoint
  load_status = saver.restore(variables_path, self._checkpoint_options)
File: "/home/ideapoke/PycharmProjects/binary_classification/venv/lib/python3.8/site-packages/tensorflow/python/training/tracking/util.py", line 1389, in restore
  base.CheckpointPosition(
File: "/home/ideapoke/PycharmProjects/binary_classification/venv/lib/python3.8/site-packages/tensorflow/python/training/tracking/base.py", line 302, in restore
  restore_ops = trackable._restore_from_checkpoint_position(self)  # pylint: disable=protected-access
File: "/home/ideapoke/PycharmProjects/binary_classification/venv/lib/python3.8/site-packages/tensorflow/python/training/tracking/base.py", line 1099, in _restore_from_checkpoint_position
  current_position.checkpoint.restore_saveables(tensor_saveables,
File: "/home/ideapoke/PycharmProjects/binary_classification/venv/lib/python3.8/site-packages/tensorflow/python/training/tracking/util.py", line 343, in restore_saveables
  new_restore_ops = functional_saver.MultiDeviceSaver(
File: "/home/ideapoke/PycharmProjects/binary_classification/venv/lib/python3.8/site-packages/tensorflow/python/training/saving/functional_saver.py", line 411, in restore
  restore_ops = restore_fn()
File: "/home/ideapoke/PycharmProjects/binary_classification/venv/lib/python3.8/site-packages/tensorflow/python/training/saving/functional_saver.py", line 394, in restore_fn
  restore_ops.update(saver.restore(file_prefix, options))
File: "/home/ideapoke/PycharmProjects/binary_classification/venv/lib/python3.8/site-packages/tensorflow/python/training/saving/functional_saver.py", line 105, in restore
  restored_tensors = io_ops.restore_v2(
File: "/home/ideapoke/PycharmProjects/binary_classification/venv/lib/python3.8/site-packages/tensorflow/python/ops/gen_io_ops.py", line 1490, in restore_v2
  return restore_v2_eager_fallback(
File: "/home/ideapoke/PycharmProjects/binary_classification/venv/lib/python3.8/site-packages/tensorflow/python/ops/gen_io_ops.py", line 1529, in restore_v2_eager_fallback
  _result = _execute.execute(b"RestoreV2", len(dtypes), inputs=_inputs_flat,
File: "/home/ideapoke/PycharmProjects/binary_classification/venv/lib/python3.8/site-packages/tensorflow/python/eager/execute.py", line 54, in quick_execute
  tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
File: "/home/ideapoke/PycharmProjects/binary_classification/venv/lib/python3.8/site-packages/gunicorn/workers/gthread.py", line 101, in handle_quit
  self.cfg.worker_int(self)
File: "/home/ideapoke/PycharmProjects/binary_classification/config_api.py", line 202, in worker_int
  for filename, lineno, name, line in traceback.extract_stack(stack):
[2022-02-19 18:50:25 +0530] [50485] [INFO] Worker exiting (pid: 50485)
[2022-02-19 18:50:28 +0530] [50483] [INFO] Shutting down: Master
[2022-02-19 18:50:48 +0530] [50558] [DEBUG] Current configuration:
  config: config_api.py
  wsgi_app: None
  bind: ['0.0.0.0:5010']
  backlog: 2048
  workers: 1
  worker_class: sync
  threads: 4
  worker_connections: 1000
  max_requests: 0
  max_requests_jitter: 0
  timeout: 1000
  graceful_timeout: 30
  keepalive: 30
  limit_request_line: 4094
  limit_request_fields: 100
  limit_request_field_size: 8190
  reload: False
  reload_engine: auto
  reload_extra_files: []
  spew: False
  check_config: False
  print_config: False
  preload_app: False
  sendfile: None
  reuse_port: False
  chdir: /home/ideapoke/PycharmProjects/binary_classification
  daemon: False
  raw_env: []
  pidfile: None
  worker_tmp_dir: None
  user: 1000
  group: 1000
  umask: 0
  initgroups: False
  tmp_upload_dir: None
  secure_scheme_headers: {'X-FORWARDED-PROTOCOL': 'ssl', 'X-FORWARDED-PROTO': 'https', 'X-FORWARDED-SSL': 'on'}
  forwarded_allow_ips: ['127.0.0.1']
  accesslog: ./log/gunicorn_logs.log
  disable_redirect_access_to_syslog: False
  access_log_format: %(h)s %(l)s %(u)s %(t)s "%(r)s" %(s)s %(b)s "%(f)s" "%(a)s"
  errorlog: ./log/gunicorn_logs.log
  loglevel: debug
  capture_output: True
  logger_class: gunicorn.glogging.Logger
  logconfig: None
  logconfig_dict: {}
  syslog_addr: udp://localhost:514
  syslog: False
  syslog_prefix: None
  syslog_facility: user
  enable_stdio_inheritance: False
  statsd_host: None
  dogstatsd_tags: 
  statsd_prefix: 
  proc_name: None
  default_proc_name: classifier_api:app
  pythonpath: None
  paste: None
  on_starting: <function OnStarting.on_starting at 0x7f17d6070e50>
  on_reload: <function OnReload.on_reload at 0x7f17d6070f70>
  when_ready: <function when_ready at 0x7f17d647bd30>
  pre_fork: <function pre_fork at 0x7f17d647bc10>
  post_fork: <function post_fork at 0x7f17d647bb80>
  post_worker_init: <function PostWorkerInit.post_worker_init at 0x7f17d6001430>
  worker_int: <function worker_int at 0x7f17d647bdc0>
  worker_abort: <function worker_abort at 0x7f17d647be50>
  pre_exec: <function pre_exec at 0x7f17d647bca0>
  pre_request: <function PreRequest.pre_request at 0x7f17d60018b0>
  post_request: <function PostRequest.post_request at 0x7f17d6001940>
  child_exit: <function ChildExit.child_exit at 0x7f17d6001a60>
  worker_exit: <function WorkerExit.worker_exit at 0x7f17d6001b80>
  nworkers_changed: <function NumWorkersChanged.nworkers_changed at 0x7f17d6001ca0>
  on_exit: <function OnExit.on_exit at 0x7f17d6001dc0>
  proxy_protocol: False
  proxy_allow_ips: ['127.0.0.1']
  keyfile: None
  certfile: None
  ssl_version: 2
  cert_reqs: 0
  ca_certs: None
  suppress_ragged_eofs: True
  do_handshake_on_connect: False
  ciphers: None
  raw_paste_global_conf: []
  strip_header_spaces: False
[2022-02-19 18:50:48 +0530] [50558] [INFO] Starting gunicorn 20.1.0
[2022-02-19 18:50:48 +0530] [50558] [DEBUG] Arbiter booted
[2022-02-19 18:50:48 +0530] [50558] [INFO] Listening at: http://0.0.0.0:5010 (50558)
[2022-02-19 18:50:48 +0530] [50558] [INFO] Using worker: gthread
[2022-02-19 18:50:48 +0530] [50558] [INFO] Server is ready. Spawning workers
[2022-02-19 18:50:48 +0530] [50560] [INFO] Booting worker with pid: 50560
[2022-02-19 18:50:48 +0530] [50560] [INFO] Worker spawned (pid: 50560)
[2022-02-19 18:50:48 +0530] [50558] [DEBUG] 1 workers
2022-02-19 18:50:50.226709: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-02-19 18:50:50.226755: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2022-02-19 18:50:56.719156: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2022-02-19 18:50:56.719215: W tensorflow/stream_executor/cuda/cuda_driver.cc:269] failed call to cuInit: UNKNOWN ERROR (303)
2022-02-19 18:50:56.719266: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (Laptop-Rakshit): /proc/driver/nvidia/version does not exist
2022-02-19 18:50:56.719577: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-02-19 18:50:56.813026: W tensorflow/core/framework/cpu_allocator_impl.cc:82] Allocation of 1009375000 exceeds 10% of free system memory.
[2022-02-19 18:56:00 +0530] [50560] [DEBUG] POST /movie_review_predictor
127.0.0.1 - - [19/Feb/2022:18:56:03 +0530] "POST /movie_review_predictor HTTP/1.1" 200 32 "-" "PostmanRuntime/7.28.4"
[2022-02-19 18:58:47 +0530] [50560] [INFO] worker received INT or QUIT signal
[2022-02-19 18:58:47 +0530] [50558] [INFO] Handling signal: int
[2022-02-19 18:58:48 +0530] [50560] [DEBUG] 
# Thread: ThreadPoolExecutor-0_0(139738187011840)
File: "/usr/lib/python3.8/threading.py", line 890, in _bootstrap
  self._bootstrap_inner()
File: "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
  self.run()
File: "/usr/lib/python3.8/threading.py", line 870, in run
  self._target(*self._args, **self._kwargs)
File: "/usr/lib/python3.8/concurrent/futures/thread.py", line 78, in _worker
  work_item = work_queue.get(block=True)

# Thread: MainThread(139740371265344)
File: "/home/ideapoke/PycharmProjects/binary_classification/venv/bin/gunicorn", line 8, in <module>
  sys.exit(run())
File: "/home/ideapoke/PycharmProjects/binary_classification/venv/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 67, in run
  WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
File: "/home/ideapoke/PycharmProjects/binary_classification/venv/lib/python3.8/site-packages/gunicorn/app/base.py", line 231, in run
  super().run()
File: "/home/ideapoke/PycharmProjects/binary_classification/venv/lib/python3.8/site-packages/gunicorn/app/base.py", line 72, in run
  Arbiter(self).run()
File: "/home/ideapoke/PycharmProjects/binary_classification/venv/lib/python3.8/site-packages/gunicorn/arbiter.py", line 202, in run
  self.manage_workers()
File: "/home/ideapoke/PycharmProjects/binary_classification/venv/lib/python3.8/site-packages/gunicorn/arbiter.py", line 551, in manage_workers
  self.spawn_workers()
File: "/home/ideapoke/PycharmProjects/binary_classification/venv/lib/python3.8/site-packages/gunicorn/arbiter.py", line 622, in spawn_workers
  self.spawn_worker()
File: "/home/ideapoke/PycharmProjects/binary_classification/venv/lib/python3.8/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
  worker.init_process()
File: "/home/ideapoke/PycharmProjects/binary_classification/venv/lib/python3.8/site-packages/gunicorn/workers/gthread.py", line 92, in init_process
  super().init_process()
File: "/home/ideapoke/PycharmProjects/binary_classification/venv/lib/python3.8/site-packages/gunicorn/workers/base.py", line 142, in init_process
  self.run()
File: "/home/ideapoke/PycharmProjects/binary_classification/venv/lib/python3.8/site-packages/gunicorn/workers/gthread.py", line 200, in run
  events = self.poller.select(1.0)
File: "/usr/lib/python3.8/selectors.py", line 468, in select
  fd_event_list = self._selector.poll(timeout, max_ev)
File: "/home/ideapoke/PycharmProjects/binary_classification/venv/lib/python3.8/site-packages/gunicorn/workers/gthread.py", line 101, in handle_quit
  self.cfg.worker_int(self)
File: "/home/ideapoke/PycharmProjects/binary_classification/config_api.py", line 202, in worker_int
  for filename, lineno, name, line in traceback.extract_stack(stack):
[2022-02-19 18:58:48 +0530] [50560] [INFO] Worker exiting (pid: 50560)
[2022-02-19 18:58:48 +0530] [50558] [WARNING] Worker with pid 50560 was terminated due to signal 2
[2022-02-19 18:58:48 +0530] [50558] [INFO] Shutting down: Master
